name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL= "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMjVmYTY5NjYtMTFkZC00YzM5LTgzNzYtODliMGM5NjQ4YmUyIiwidGVuYW50X2lkIjoiOWVkY2Y4YzAzMWE1YWE4ZTkwZGM4YjczYTkxNmFhYmExZGEyZmI1NDEyNTQ3MzZlMzEwMjMwNGIwOTI5NzkxNyIsImludGVybmFsX3NlY3JldCI6IjhlYjQ3MTEyLTRkODgtNDE4Zi04MWQzLTJmZTY3YWIwNTdjNyJ9.lbhjXQguXs6fwsBIgqTnSpyFPvC_oJrap75b4QfjdEE"# [[kv_namespaces]]"
JWT_SECRET = "secretkey"
# MY_VAR = "my-variable"
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""
